Repository oap-project/native-sql-engine, pull requests merged in 2021-04, with the labels that each got.

#270 [NSE-261] ArrowDataSource: Add S3 Support
  arrow-data-source/pom.xml
  arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowUtils.scala
  arrow-data-source/standard/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTest.scala
  native-sql-engine/core/pom.xml
Labels: enhancement

#281 [NSE-280] bump cmake to 3.16
  native-sql-engine/cpp/CMakeLists.txt
  native-sql-engine/cpp/src/CMakeLists.txt
Labels: needsbackport

#284 [NSE-283] Pick S3/CSV supports to OAP 1.1
  .github/workflows/tpch.yml
  .github/workflows/unittests.yml
  README.md
  arrow-data-source/.travis.yml
  arrow-data-source/README.md
  arrow-data-source/docs/ApacheArrowInstallation.md
  arrow-data-source/pom.xml
  arrow-data-source/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowUtils.scala
  arrow-data-source/standard/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTest.scala
  docs/ApacheArrowInstallation.md
  docs/Configuration.md
  docs/Installation.md
  docs/Prerequisite.md
  native-sql-engine/core/pom.xml
  native-sql-engine/cpp/src/CMakeLists.txt
  native-sql-engine/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
  pom.xml
Labels: backport

#246 [NSE-245]Adding columnar RDD cache support
  native-sql-engine/core/src/main/scala/com/intel/oap/ColumnarGuardRule.scala
  native-sql-engine/core/src/main/scala/com/intel/oap/ColumnarPlugin.scala
  native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarInMemoryRelation.scala
  native-sql-engine/core/src/main/scala/com/intel/oap/execution/ColumnarInMemoryTableScanExec.scala
  native-sql-engine/core/src/main/scala/com/intel/oap/expression/ColumnarConditionProjector.scala
  native-sql-engine/core/src/main/scala/com/intel/oap/expression/ConverterUtils.scala
  native-sql-engine/core/src/main/scala/org/apache/spark/sql/columnar/CachedBatchSerializer.scala
  native-sql-engine/core/src/main/scala/org/apache/spark/sql/execution/columnar/InMemoryRelation.scala
Labels: feature request
